name: Run generate_weekly.py on api_data.json commit

on:
  workflow_run:
    workflows: ["Run generate_data.py"]
    types:
      - completed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script needs

    - name: Run generate_weekly.py
      run: python generate_weekly.py

    - name: Extract current year from seasons.json
      id: year
      run: |
        YEAR=$(python -c "import json; \
        with open('seasons.json') as f: \
            data = json.load(f); \
        print(next(s['id'] for s in data if s.get('current') == True))")
        echo "::set-output name=current_year::$YEAR"

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add weeklydata_${{ steps.year.outputs.current_year }}.json
        git add seasondata_${{ steps.year.outputs.current_year }}.json
        git commit -m "Update data for ${{ steps.year.outputs.current_year }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
