name: Process Data Workflows

on:
  schedule:
    - cron: "0 14 * * 2"  # Runs at 9AM ET every Tuesday (14:00 UTC)
  push:
    branches:
      - main
    paths:
      - '*/api_data.json'
      - '*/weekly.json'
      - '*/season.json'
      - 'seasons.json'
  workflow_dispatch:

jobs:
  generate-data:
    name: Run generate_data.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r reqauirements.txt

      - name: Run generate_data.py
        run: python generate_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */*.json seasons.json
          git diff --cached --quiet || git commit -m 'Update data files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}

  generate-weekly:
    name: Run generate_weekly.py
    runs-on: ubuntu-latest
    needs: generate-data
    if: ${{ needs.generate-data.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run generate_weekly.py
        run: python generate_weekly.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */*.json
          git diff --cached --quiet || git commit -m 'Update weekly data files'
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-payouts:
    name: Update Payouts
    runs-on: ubuntu-latest
    needs: generate-weekly
    if: ${{ needs.generate-weekly.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fantasy_payouts.py
        run: python fantasy_payouts.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */*.json
          git diff --cached --quiet || git commit -m 'Update payouts data files'
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
