name: Process Data Workflows

on:
  schedule:
    - cron: "0 14 * * *"  # Runs daily at 9AM ET (14:00 UTC)
  push:
    branches:
      - main
    paths:
      - '*/api_data.json'
      - '*/weekly.json'
      - '*/season.json'
      - 'seasons.json'
  workflow_dispatch:

jobs:
  process-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements.txt

      - name: Run generate_data.py
        env:
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        run: python generate_data.py

      - name: Commit data updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */*.json seasons.json
          git diff --cached --quiet || git commit -m 'Update data files'
          git push

      - name: Run generate_weekly.py
        run: python generate_weekly.py

      - name: Commit weekly updates
        run: |
          git add */*.json
          git diff --cached --quiet || git commit -m 'Update weekly data files'
          git push

      - name: Run fantasy_payouts.py
        run: python fantasy_payouts.py

      - name: Commit payout updates
        run: |
          git add */*.json
          git diff --cached --quiet || git commit -m 'Update payouts data files'
          git push

