name: Run generate_data.py

on:
  schedule:
    # - cron: "0 14 * * 2"  # Runs at 9AM ET every Tuesday (14:00 UTC)
    - cron: "*/5 * * * *"
  push:
    paths:
      - 'api_data.json'
    branches:
      - main
      
jobs:
  file-deletion:
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, '[delete]')
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'  # Specify the Python version you need

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install requests  # Add any other dependencies your script needs

          - name: Run generate_data.py
            run: python generate_data.py

          - name: Commit and push changes
            run: |
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add api_data.json
              git commit -m "Update api_data.json weekly Tuesday Morning at 9AM ET"
              git push
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script needs

    - name: Run generate_data.py
      run: python generate_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add api_data.json
        git commit -m "Update api_data.json weekly Tuesday Morning at 9AM ET"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
