name: Run generate_data.py

on:
  schedule:
    - cron: "0 14 * * 2"  # Runs at 9AM ET every Tuesday (14:00 UTC)
  push:
    branches:
      - main
    paths:
      - 'api_data.json'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script needs

    - name: Run generate_data.py
      run: python generate_data.py
    
    - name: Extract current year from seasons.json
      id: year
      run: |
        YEAR=$(python -c "import json; \
        with open('seasons.json') as f: \
            data = json.load(f); \
        print(next(s['id'] for s in data if s.get('current') == True))")
        echo "::set-output name=current_year::$YEAR"
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add api_data${{ steps.year.outputs.current_year }}.json
        git commit -m 'Update api_data${{ steps.year.outputs.current_year }}.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}