name: Run generate_data.py

on:
  schedule:
    - cron: "0 14 * * 2"  # Runs at 9AM ET every Tuesday (14:00 UTC)
  push:
    branches:
      - main
    paths:
      - 'api_data.json'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script needs

    - name: Run generate_data.py
      run: python generate_data.py
