name: Update Payouts

on:
  workflow_run:
    workflows: ["Run generate_weekly.py on api_data.json commit"]
    types:
      - completed

jobs:
  update-payouts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python fantasy_payouts.py
      
      - name: Extract current year from seasons.json
        id: year
        run: |
          YEAR=$(python -c "import json; \
          with open('seasons.json') as f: \
              data = json.load(f); \
          print(next(s['id'] for s in data if s.get('current') == True))")
          echo "::set-output name=current_year::$YEAR"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add payouts_${{ steps.year.outputs.current_year }}.json
          git commit -m "Update payouts.json after changes to weeklydata.json or seasondata.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
